<a href="https://colab.research.google.com/github/matiashermida22/gestiondeeventos/blob/main/proyecto_integrador_1_resuelto.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1 - Importo las librerías a utilizar

In [1]:
from datetime import datetime, timezone
import requests
import pandas as pd
from bs4 import BeautifulSoup

# 2 - Extraigo la información de la página Whale Alert

In [ ]:
url_whale_alert = "https://whale-alert.io/whales.html"
def get_whale_alert_df(url=url_whale_alert):
    response = requests.get(url)
    response.raise_for_status()

    soup = BeautifulSoup(response.content, "html.parser")
    rows = soup.find("table", class_="table").find("tbody").find_all("tr")

    records = []
    for row in rows:
        th = row.find("th", {"scope": "row"})
        img = th.find("img")
        coin = img["alt"].strip() if img else th.get_text(strip=True)

        tds = row.find_all("td")
        if len(tds) < 2:
            continue

        records.append({
            "crypto": coin,
            "known": tds[0].get_text(strip=True),
            "unknown": tds[1].get_text(strip=True),
        })

    return pd.DataFrame(records)

In [ ]:
whale_alert_raw = get_whale_alert_df()

In [ ]:
whale_alert_raw

         crypto         known       unknown
0       Bitcoin   $50,000,000  $100,000,000
1      Ethereum   $50,000,000  $100,000,000
2   Stablecoins  $100,000,000  $200,000,000
3         ERC20   $20,000,000   $50,000,000
4        Ripple   $50,000,000  $100,000,000
5          Tron   $20,000,000   $50,000,000
6          Tron   $20,000,000   $50,000,000
7       Polygon   $20,000,000   $50,000,000
8        Solana    50,000,000  $100,000,000
9           Bch   $20,000,000   $50,000,000
10     Algorand   $20,000,000   $50,000,000
11     Litecoin   $20,000,000   $50,000,000
12     Dogecoin   $20,000,000   $50,000,000
13      Cardano   $20,000,000   $50,000,000
14       Plasma   $20,000,000   $50,000,000

# Agrego Timestamp

In [ ]:
whale_alert_raw['timestamp'] = datetime.now(timezone.utc)

In [ ]:
whale_alert_raw

         crypto         known       unknown                        timestamp
0       Bitcoin   $50,000,000  $100,000,000 2026-03-30 03:31:49.125744+00:00
1      Ethereum   $50,000,000  $100,000,000 2026-03-30 03:31:49.125744+00:00
2   Stablecoins  $100,000,000  $200,000,000 2026-03-30 03:31:49.125744+00:00
3         ERC20   $20,000,000   $50,000,000 2026-03-30 03:31:49.125744+00:00
4        Ripple   $50,000,000  $100,000,000 2026-03-30 03:31:49.125744+00:00
5          Tron   $20,000,000   $50,000,000 2026-03-30 03:31:49.125744+00:00
6          Tron   $20,000,000   $50,000,000 2026-03-30 03:31:49.125744+00:00
7       Polygon   $20,000,000   $50,000,000 2026-03-30 03:31:49.125744+00:00
8        Solana    50,000,000  $100,000,000 2026-03-30 03:31:49.125744+00:00
9           Bch   $20,000,000   $50,000,000 2026-03-30 03:31:49.125744+00:00
10     Algorand   $20,000,000   $50,000,000 2026-03-30 03:31:49.125744+00:00
11     Litecoin   $20,000,000   $50,000,000 2026-03-30 03:31:49.125744+00:00
12     Dogecoin   $20,000,000   $50,000,000 2026-03-30 03:31:49.125744+00:00
13      Cardano   $20,000,000   $50,000,000 2026-03-30 03:31:49.125744+00:00
14       Plasma   $20,000,000   $50,000,000 2026-03-30 03:31:49.125744+00:00

## Elimino Duplicados

In [ ]:
whale_alert = whale_alert_raw.drop_duplicates()

In [ ]:
whale_alert

         crypto         known       unknown                        timestamp
0       Bitcoin   $50,000,000  $100,000,000 2026-03-30 03:31:49.125744+00:00
1      Ethereum   $50,000,000  $100,000,000 2026-03-30 03:31:49.125744+00:00
2   Stablecoins  $100,000,000  $200,000,000 2026-03-30 03:31:49.125744+00:00
3         ERC20   $20,000,000   $50,000,000 2026-03-30 03:31:49.125744+00:00
4        Ripple   $50,000,000  $100,000,000 2026-03-30 03:31:49.125744+00:00
5          Tron   $20,000,000   $50,000,000 2026-03-30 03:31:49.125744+00:00
7       Polygon   $20,000,000   $50,000,000 2026-03-30 03:31:49.125744+00:00
8        Solana    50,000,000  $100,000,000 2026-03-30 03:31:49.125744+00:00
9           Bch   $20,000,000   $50,000,000 2026-03-30 03:31:49.125744+00:00
10     Algorand   $20,000,000   $50,000,000 2026-03-30 03:31:49.125744+00:00
11     Litecoin   $20,000,000   $50,000,000 2026-03-30 03:31:49.125744+00:00
12     Dogecoin   $20,000,000   $50,000,000 2026-03-30 03:31:49.125744+00:00
13      Cardano   $20,000,000   $50,000,000 2026-03-30 03:31:49.125744+00:00
14       Plasma   $20,000,000   $50,000,000 2026-03-30 03:31:49.125744+00:00